Build Docker dev image
luxonis/depthai-docs-website pull request #135
Opened 2021-01-25 22:03 UTC by pamolloy

2021-01-25 22:04 UTC, pamolloy commented
Once I actually get DepthAI running in a container it may require updating this, but it is perfectly functional now as a base image.

2021-01-25 23:50 UTC, themarpe requested changes
I don't know whether this is the right location for this, WRT having other docker images as well.  
And another thing to discuss is the naming - maybe we rather have this be a depthai base and the depthai for a fully fledged depthai image?

2021-01-25 23:50 UTC, themarpe commented on .github/workflows/docker-hub.yml
> +      - name: Set up QEMU
Is QEMU needed?

2021-01-26 11:38 UTC, VanDavv commented
I would opt to use https://github.com/luxonis/depthai-docker repository for this

2021-01-26 14:15 UTC, pamolloy commented on .github/workflows/docker-hub.yml
> +      - name: Set up QEMU
Nope! It is something I'd like to implement at some point, but not worth adding here.

2021-01-26 14:28 UTC, pamolloy commented
@VanDavv @themarpe The reason I added the Dockerfile here is because it uses `install_dependencies.sh`. I just added the condition (which I removed while debugging) that it only builds an image when `install_dependencies.sh` is modified. Hopefully that works in conjunction with `push: branches: master`. :crossed_fingers: 

Note that the installation instructions that document the use of `install_dependencies.sh` will move to `python-depthai` in Gen 2, so I assume `install_dependencies.sh` will also move to `python-depthai`. And naturally the `Dockerfile` would move too.

I don't think the Dockerfile needs it's own repository, not to mention the above point about keeping it close to `install_dependencies.sh`.

2021-01-26 20:49 UTC, themarpe approved these changes

2021-01-26 22:08 UTC, merged