scale frame pixels to the range [0,1]
luxonis/depthai-docs-website pull request #157
Opened 2021-03-18 21:55 UTC by cafemoloko

model optimizer parameters for scaling frame pixels to the range [0,1]

2021-03-18 22:01 UTC, Luxonis-Brandon commented
Thanks!

2021-03-19 02:55 UTC, szabi-luxonis requested changes

2021-03-19 02:55 UTC, szabi-luxonis commented on source/pages/faq.rst
> +:code:`--data_type=FP16 --scale_values [255,255,255]`
mean values should be added to in case some wants to scale to [-1,1] range, e.g. for mobilenet:
`--scale_values [127.5, 127.5, 127.5] --mean_values [127.5, 127.5, 127.5]`
First the mean values are substracted from pixel values, than the result is scaled.

Also add a link for all the options from openvino:
https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Converting_Model_General.html

2021-03-22 20:18 UTC, szabi-luxonis approved these changes

2021-03-23 07:05 UTC, merged