Update AutoFocus AWB, etc. settings to Gen2
luxonis/depthai-docs-website pull request #161
Opened 2021-03-23 19:04 UTC by Luxonis-Brandon

Update the FAQ to reference Gen2 controls instead of Gen1 for autofocus, etc.

2021-03-23 19:06 UTC, Luxonis-Brandon commented
Feel free to change anything/everything @VanDavv / @alex-luxonis .  Just wanted to get these updated so that they're pointing to Gen2 examples.  I'll try to go through the FAQ and do this for many other things that are in it which point to Gen2 right now.

2021-03-29 11:53 UTC, VanDavv approved these changes

2021-03-29 11:57 UTC, VanDavv requested changes

2021-03-29 11:57 UTC, VanDavv commented on source/pages/faq.rst
> +And see here
Was this added unintentionally?

2021-04-07 11:36 UTC, VanDavv approved these changes
LGTM

2021-04-07 11:36 UTC, merged