FAQ update: letterboxing
luxonis/depthai-docs-website pull request #162
Opened 2021-03-25 18:23 UTC by cafemoloko

added: how to do letterboxing (issue from discord)

2021-03-26 05:00 UTC, Luxonis-Brandon approved these changes

2021-03-29 12:10 UTC, VanDavv requested changes

2021-03-29 12:10 UTC, VanDavv commented on source/index.rst
> +DepthAI is a platform - a complete ecosystem of custom `hardware <https://github.com/luxonis/depthai-hardware>`__, firmware, `software <https://docs.luxonis.com/projects/api/en/latest/>`__, and AI tr
I would also add a link to AI training that points to https://github.com/luxonis/depthai-ml-training

2021-03-29 12:10 UTC, VanDavv commented on source/index.rst
> +.. list-table:: API
Can we use the html components that were used on master?

**current**
![image](https://user-images.githubusercontent.com/5244214/112833835-8faeef80-9097-11eb-8833-2234940b4b6e.png)

**this PR**
![image](https://user-images.githubusercontent.com/5244214/112833774-7d34b600-9097-11eb-814f-02f9db6c5ef0.png)

2021-03-29 12:10 UTC, VanDavv commented on source/index.rst
> +    - `Get started with GUI <https://docs.luxonis.com/projects/gui/en/latest/#> `__
this table is not rendered at all, incorrect indent in this line (dashes should match their position)

2021-03-29 12:10 UTC, VanDavv commented on source/pages/faq.rst
> +#. Using our C++ SPI API (see `here <https://github.com/luxonis/depthai-spi-api>`_),
please keep double `__`, single ones also create a named header (so `` `test <link>`_ `` will create a header named `test`, whereas `` `test <link>`__ `` will not create any)
This causes a warning in RTD build, since we had a lot of duplicated headers called `here` (as we tend to add links like `` see `here <link>`__ ``)

2021-04-06 20:32 UTC, cafemoloko commented on source/index.rst
> +.. list-table:: API
change reverted in the last commit (html components restored)

2021-04-07 11:34 UTC, VanDavv requested changes
In this PR, the changes from #165 are also present

2021-04-07 11:34 UTC, VanDavv commented on source/pages/faq.rst
> +#. Using our standalone flashing utility to flash a depthai application for standalone boot (as part of Pipeline Builder Gen2, leveraging our SBR Util `here <https://github.com/luxonis/sbr-util>`_).
use double `__`

2021-04-07 11:34 UTC, VanDavv commented on source/pages/faq.rst
> + - DepthAI Mode (USB, using our USB API, `here Python API <https://docs.luxonis.com/projects/api/en/latest/>`_) - this uses the onboard cameras directly into the Myriad X, and boots the firmware over
use double `__`

2021-04-08 18:34 UTC, closed without merging