Update calibration docs
luxonis/depthai-docs-website pull request #210
Opened 2021-06-16 11:36 UTC by VanDavv

Updated the calibration documentation to reflect the current Gen2 calibration script possibilities. Requires https://github.com/luxonis/depthai/pull/396 to be merged first

2021-06-16 18:36 UTC, saching13 requested changes

2021-06-16 18:36 UTC, saching13 commented on source/pages/calibration.rst
>      - :code:`-s SQUARE_SIZE_IN_CM`, :code:`--square_size_cm SQUARE_SIZE_IN_CM`: Measure the square size of the printed checkerboard in centimeters.
`markerSizeCm` need to add marker size too.

2021-06-16 18:36 UTC, saching13 commented on source/pages/calibration.rst
> +    - :code:`-brd BOARD`, :code:`--board BOARD`: BW1097, BW1098OBC - Board type from resources/boards/ (not case-sensitive, if you're using OAK-D please choose BW1098OBC). Or path to a custom .json b
`Mutually exclusive with [-fv -b -w], which allow manual specification of field of view, baseline, and camera orientation (swapped or not-swapped).` This is not supported. So need to write the board json file as argument. SInce  we need all the information in that which is written to EEPROM in the same script.

2021-06-16 18:36 UTC, saching13 commented on source/pages/calibration.rst
> +    For example, the arguments for the :ref:`OAK-D <bw1098obc>` look like the following if the square size is 2.35 cm:
look like the following if the square size is 2.35 cm and Marker size is <Size in CM>:

2021-06-16 18:36 UTC, saching13 commented on source/pages/calibration.rst
`python3 calibrate.py -s 2.35 -brd bw1098obc` => `python3 calibrate.py -s 2.35 -ms <size of marker> -brd bw1098obc`

2021-06-16 18:36 UTC, saching13 commented on source/pages/calibration.rst
Add marker size here too.

2021-06-16 18:36 UTC, saching13 commented on source/pages/calibration.rst
Marker size

2021-06-16 18:36 UTC, saching13 commented on source/pages/calibration.rst
> +If successful, calibration files (:code:`left_mesh.calib` and :code:`right_mesh.calib`) will be created at :code:`depthai/resources/`
If successful, calibration data will be written to eeprom and a copy of it will be created in files under :code:`depthai/resources/` as :code:`<Device Mx ID>.json` if device is connected. And as :code:`depthai_calib.json` when it is not connected.

It will also create mesh files named :code:`left_mesh.calib` and :code:`right_mesh.calib` under code:`depthai/resources/` which can be used to overcome distortions in stereo node for camera modules with distortions. <br class="Apple-interchange-newline">

2021-06-17 09:24 UTC, VanDavv commented
Thanks @saching13, I was not aware of the `-ms` flag

2021-06-18 16:44 UTC, saching13 commented on source/pages/calibration.rst
> +It will also create the mesh files named :code:`left_mesh.calib` and :code:`right_mesh.calib` under code:`depthai/resources/`
:code:`depthai/resources/` Colon is missing here.. it is not rendered properly.

2021-06-18 16:46 UTC, saching13 commented on source/pages/calibration.rst
> +      :target: https://github.com/luxonis/depthai/raw/fix_calibration/charuco_297x210_8x11_20_DICT_4X4.png
This is not rendered. Is that because it is in debug mode or something ?

2021-06-18 16:47 UTC, saching13 approved these changes
Apart from these two comments, it's good to merge.

2021-06-18 21:06 UTC, merged