Ai refactor
luxonis/depthai-docs-website pull request #302
Opened 2022-02-10 10:05 UTC by Erol444

![image](https://user-images.githubusercontent.com/18037362/153384379-abe9adbb-3f0a-45b4-8969-3cb6a66fd1ef.png)

2022-02-10 10:38 UTC, cafemoloko requested changes

2022-02-10 10:38 UTC, cafemoloko commented on source/index.rst
> +   Hardware Products <https://docs.luxonis.com/projects/hardware/en/latest/>
```suggestion
   Hardware Documentation <https://docs.luxonis.com/projects/hardware/en/latest/>
```

2022-02-10 10:38 UTC, cafemoloko commented on source/index.rst
>  DepthAI's documentation
```suggestion
DepthAI's Documentation
```

2022-02-10 10:38 UTC, cafemoloko commented on source/index.rst
>  Demo script
```suggestion
Demo Script
```

2022-02-10 10:38 UTC, cafemoloko commented on source/pages/ai_ml_nn.rst
> +Model performance
```suggestion
Model Performance
```

2022-02-10 10:38 UTC, cafemoloko commented on source/pages/troubleshooting.rst
>  Output from DepthAI keeps freezing
```suggestion
Output from DepthAI Keeps Freezing
```

2022-02-10 10:38 UTC, cafemoloko commented on source/pages/tutorials/first_steps.rst
>  Connect the DepthAI device
```suggestion
Connect the DepthAI Device
```

2022-02-10 10:38 UTC, cafemoloko commented on source/pages/troubleshooting.rst
>  Failed to boot the device: 1.3-ma2480, err code 3
```suggestion
Failed to Boot the Device: 1.3-ma2480, err code 3
```

2022-02-10 10:38 UTC, cafemoloko commented on source/pages/tutorials/first_steps.rst
> +After unboxing your DepthAI package, you will receive your device together with a USB-C cable.
OAK-D-Lite doesn't come with a USB cable.

2022-02-10 10:38 UTC, cafemoloko commented on source/index.rst
>  In this section, you'll find an inspiration what can you build right away with DepthAI
```suggestion
In this section, you'll find an inspiration what can you build right away with DepthAI.
```

2022-02-11 14:21 UTC, themarpe approved these changes

2022-02-11 14:22 UTC, merged