Openvino tensor representation documentation
luxonis/depthai-docs-website pull request #93
Opened 2020-10-08 11:00 UTC by szabi-luxonis

Added support for Ubuntu 20.04 (ruby 2.7.0).
Added documentation for new API.

2020-10-08 11:17 UTC, VanDavv requested changes

2020-10-08 11:17 UTC, VanDavv commented on api.md
> +* [__[ Union[int, str] ]__](#nnetpacket_getitem) -> numpy.ndarray
Method name is missing
![image](https://user-images.githubusercontent.com/5244214/95451332-ed277680-0967-11eb-8a8d-b0c6e89dd6a2.png)

2020-10-08 11:17 UTC, VanDavv commented on api.md
> +{: #Detections}
I would skip the Containers classes. They behave like lists and serve a similar purpose, so I think we're fine just skipping them as there's nothing special about them

2020-10-08 11:17 UTC, VanDavv commented on api.md
> +If config file is emitted there is no decoding done on device <==> `output_format` is set to `raw`. The decoding must be done on host side, by the user.
typo? Should it be `omitted`?

2020-10-08 11:20 UTC, szabi-luxonis commented on api.md
> +* [__[ Union[int, str] ]__](#nnetpacket_getitem) -> numpy.ndarray
It's the operator [], so nnet_packet[0] is equivalent to nnet_packet.get_tensor(0)

2020-10-08 11:28 UTC, VanDavv commented on api.md
> +* [__[ Union[int, str] ]__](#nnetpacket_getitem) -> numpy.ndarray
Oh, ok. So maybe just name it ]`__getitem__`](https://docs.python.org/3/reference/datamodel.html#object.__getitem__)?
I was a bit confused seeing this and was not aware that it resolves to `[]`

2020-10-09 15:22 UTC, szabi-luxonis commented on api.md
> +{: #Detections}
We still need to document it, otherwise people won't know that it behaves like a container class.

2020-10-09 16:45 UTC, VanDavv approved these changes

2020-10-09 22:31 UTC, merged