Two homography features
luxonis/depthai-docs-website pull request #96
Opened 2020-10-12 23:24 UTC by saching13

added calibration api along with rectified left and rectified right stream information to the documentation.

2020-10-12 23:33 UTC, Luxonis-Brandon reviewed
I'm going to try changing that formatting and a bit of the wording in there.

2020-10-12 23:33 UTC, Luxonis-Brandon commented on api.md
> +  if you have been using old build system and recently moved to the new build system then to enable `get_left_homography()`, `get_left_intrinsic()`, `get_right_intrinsic()`, `get_rotation()`, `get_tr
This renders funny:
![image](https://user-images.githubusercontent.com/32992551/95799041-b1b2e200-0cb0-11eb-97aa-aeb840fabb60.png)

I think from here it shouldn't have `Note` in there but instead `error` and be like below:

```
<div class="alert alert-primary" role="alert">
<i class="material-icons">
error
</i>
  Using the RPi Compute Edition ([BW1097](https://docs.luxonis.com/products/bw1097/)) or USB3 Onboard Cameras Edition ([BW1098OBC](https://docs.luxonis.com/products/bw1098obc/))? <strong>Your unit comes pre-calibrated.</strong><br/>
</div>
```

From the top of here:
https://github.com/luxonis/depthai-docs-website/blob/master/_includes/stereo_calibration.md

2020-10-12 23:37 UTC, saching13 commented on api.md
> +  if you have been using old build system and recently moved to the new build system then to enable `get_left_homography()`, `get_left_intrinsic()`, `get_right_intrinsic()`, `get_rotation()`, `get_tr
That is weird. WIll change it.

2020-10-22 10:17 UTC, VanDavv commented
@saching13 I can see you're operating on an outdated branch (and some of the changes overlap, like available stream names). Could you rebase / merge with latest master?
![image](https://user-images.githubusercontent.com/5244214/96858471-95f1cd80-1460-11eb-9916-fa5fdd0440fd.png)

2020-10-22 10:19 UTC, VanDavv requested changes
@saching13 I can see you're operating on an outdated branch (and some of the changes overlap, like available stream names). Could you rebase / merge with latest master?
![image](https://user-images.githubusercontent.com/5244214/96858471-95f1cd80-1460-11eb-9916-fa5fdd0440fd.png)

2020-10-22 16:21 UTC, saching13 commented
@VanDavv Done.

2020-10-22 16:26 UTC, Luxonis-Brandon commented
Sorry this one was my fault I think.

2020-10-26 20:27 UTC, merged